# version: "3.8"

services:

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    networks:
      - network
    volumes:
      - volume_mariadb:/var/lib/mysql
    env_file: .env

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - network
    volumes:
      - volume_wordpress:/var/www/html
    env_file: .env

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - network
    volumes:
      - volume_wordpress:/var/www/html

networks:
  network:

volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/iassafe/data/mariadb
      o: bind

  volume_wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/iassafe/data/wordpress
      o: bind
